### ISSUE TITLE
Release for Elm 0.17

### ISSUE THREAD

**Issue by danneu** [rhofour/elm-pairing-heap#4]
Edit: Oh, there's already a pull request.

**Comment by rhofour** [comment]
Yeah, I'd just been dragging my feet about that. Thanks for the reminder.

**Comment by danneu** [comment]
@rhofour I see a week ago it got 0.18 support. Just needs a elm-packages release now when you get a chance.

**Comment by rhofour** [comment]
@danneu Thanks again for the reminder. Should be published now.

**Comment by danneu** [comment]
@rhofour good stuff, thanks
